### ISSUE TITLE
Results pagina div in div

### ISSUE THREAD

**Issue by spacejump3** [spacejump3/blok-tech-team-B#10]
In de results pagina, als er meer dan 1 resultaat tevoorschijn komt klopt de styling ineens niet meer. DIt komt omdat er een div in een div zit. Het lijkt alsof de resultaten onder elkaar staan, maar in werkelijkheid zitten ze in elkaar. Pls fix.

**Comment by joppekoops** [comment]
Er werd één div'je niet gesloten, waardoor alle resultaten in elkaar stonden.
