### ISSUE TITLE
Welke taal kiezen we voor de applicatie?

### ISSUE THREAD

**Issue by joppekoops** [spacejump3/blok-tech-team-B#22]
Een deel van de applicatie is in het Engels en een ander deel in het Nederlands. Ik dacht dat we de applicatie helemaal in het Engels zouden doen, maar Nederlands is ook goed. In ieder geval moeten we één taal kiezen. Doen we Nederlands of Engels?

Delen in het Nederlands:

- Header
- Profiel
- Inloggen
- Registreren

Delen in het Engels:

- Home
- Resultaten (behalve 'meer info' link)
- Enkel Resultaat
- Post formulier

**Comment by thimogagliano** [comment]
Ik ben het eens met Stephan, ik heb ook dingen in het nederlands nog staan en zal die ook nog veranderen naar engels.

**Comment by lucaoudejans** [comment]
Yes ik ben het eens met engels, ik zal mijn delen ook aanpassen

**Comment by joppekoops** [comment]
Alles is nu Engels
