### ISSUE TITLE
De fonts in de SCSS werken niet

### ISSUE THREAD

**Issue by joppekoops** [spacejump3/blok-tech-team-B#9]
De fonts uit die in de SCSS zijn gelinkt laden niet op de pagina waarschijnlijk omdat de bestandsnamen niet kloppen. Maar ik weet niet of de font in de SCSS het `Recky.ttf` bestand moet zijn in de `/fonts` folder. @LisaxLF zou jij de goede font kunnen linken of toevoegen?

**Comment by LisaxLF** [comment]
Hoi Joppe, het is gelukt hoor!
